# Generated by Django 6.0.2 on 2026-02-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_equipmentdata_flowrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
