# Generated by Django 6.0.2 on 2026-02-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_equipmentdata_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
